/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './home';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from 'ionic-angular/components/toolbar/toolbar';
import * as import12 from 'ionic-angular/components/navbar/navbar';
import * as import13 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import14 from 'ionic-angular/components/content/content';
import * as import15 from '@angular/common/src/directives/ng_for';
import * as import16 from 'ionic-angular/config/config';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from 'ionic-angular/navigation/view-controller';
import * as import19 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import20 from 'ionic-angular/components/app/app';
import * as import21 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import23 from 'ionic-angular/util/keyboard';
import * as import24 from '@angular/core/src/zone/ng_zone';
import * as import25 from 'ionic-angular/components/tabs/tabs';
import * as import26 from '@angular/core/src/linker/template_ref';
import * as import27 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import28 from 'ionic-angular/components/card/card';
import * as import29 from 'ionic-angular/components/grid/grid';
import * as import30 from 'ionic-angular/components/button/button';
import * as import31 from 'ionic-angular/components/icon/icon';
import * as import32 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import33 from '@angular/core/src/security';
var renderType_HomePage_Host:import0.RenderComponentType = (null as any);
class _View_HomePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HomePage_0_4:import3.HomePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage_Host0,renderType_HomePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('home-page',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HomePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HomePage_0_4 = new import3.HomePage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._HomePage_0_4,([] as any[]),compView_0);
    compView_0.create(this._HomePage_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HomePage) && (0 === requestNodeIndex))) { return this._HomePage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_HomePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HomePage_Host === (null as any))) { (renderType_HomePage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_HomePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomePageNgFactory:import10.ComponentFactory<import3.HomePage> = new import10.ComponentFactory<import3.HomePage>('home-page',viewFactory_HomePage_Host0,import3.HomePage);
const styles_HomePage:any[] = ([] as any[]);
var renderType_HomePage:import0.RenderComponentType = (null as any);
class _View_HomePage0 extends import1.AppView<import3.HomePage> {
  _el_0:any;
  _Header_0_3:import11.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import12.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import13.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Content_9_4:import14.Content;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _TemplateRef_11_5:any;
  _NgFor_11_6:import15.NgFor;
  _text_12:any;
  _text_13:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage0,renderType_HomePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import11.Header(this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import18.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','primary');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import19.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import12.Navbar(this.parentInjector.get(import20.App),this.parentInjector.get(import18.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import21.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import13.ToolbarTitle(this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import11.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'Home',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'padding','');
    this._appEl_9 = new import2.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import22.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import14.Content(this.parentInjector.get(import16.Config),new import17.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import20.App),this.parentInjector.get(import23.Keyboard),this.parentInjector.get(import24.NgZone),this.parentInjector.get(import18.ViewController,(null as any)),this.parentInjector.get(import25.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_11 = new import2.AppElement(11,9,this,this._anchor_11);
    this._TemplateRef_11_5 = new import26.TemplateRef_(this._appEl_11,viewFactory_HomePage1);
    this._NgFor_11_6 = new import15.NgFor(this._appEl_11.vcRef,this._TemplateRef_11_5,this.parentInjector.get(import27.IterableDiffers),this.ref);
    this._text_12 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._appEl_11,
        this._text_12
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._text_13
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import12.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4; }
    if (((token === import11.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import26.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import15.NgFor) && (11 === requestNodeIndex))) { return this._NgFor_11_6; }
    if (((token === import14.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Content_9_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_0:any = 'primary';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Navbar_2_4.color = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    changes = (null as any);
    const currVal_4:any = this.context.items;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgFor_11_6.ngForOf = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._NgFor_11_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_11_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_9_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_9_4.ngOnDestroy();
  }
}
export function viewFactory_HomePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.HomePage> {
  if ((renderType_HomePage === (null as any))) { (renderType_HomePage = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_HomePage,{})); }
  return new _View_HomePage0(viewUtils,parentInjector,declarationEl);
}
class _View_HomePage1 extends import1.AppView<any> {
  _el_0:any;
  _Card_0_3:import28.Card;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _CardContent_4_3:import28.CardContent;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _Row_13_3:import29.Row;
  _text_14:any;
  _el_15:any;
  _Col_15_3:import29.Col;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _Button_17_4:import30.Button;
  _text_18:any;
  _el_19:any;
  _Icon_19_3:import31.Icon;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _Col_23_3:import29.Col;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _Button_25_4:import30.Button;
  _text_26:any;
  _el_27:any;
  _Icon_27_3:import31.Icon;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage1,renderType_HomePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_0_3 = new import28.Card(this.parent.parentInjector.get(import16.Config),new import17.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'img',(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'ion-card-content',(null as any));
    this._CardContent_4_3 = new import28.CardContent();
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h2',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','card-title');
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'p',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n\n     ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_0,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_13,'no-padding','');
    this._Row_13_3 = new import29.Row();
    this._text_14 = this.renderer.createText(this._el_13,'\n       ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'ion-col',(null as any));
    this._Col_15_3 = new import29.Col();
    this._text_16 = this.renderer.createText(this._el_15,'\n         ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'button',(null as any));
    this.renderer.setElementAttribute(this._el_17,'clear','');
    this.renderer.setElementAttribute(this._el_17,'color','danger');
    this.renderer.setElementAttribute(this._el_17,'icon-left','');
    this.renderer.setElementAttribute(this._el_17,'ion-button','');
    this.renderer.setElementAttribute(this._el_17,'small','');
    this._appEl_17 = new import2.AppElement(17,15,this,this._el_17);
    var compView_17:any = import32.viewFactory_Button0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Button_17_4 = new import30.Button((null as any),'',this.parent.parentInjector.get(import16.Config),new import17.ElementRef(this._el_17),this.renderer);
    this._appEl_17.initComponent(this._Button_17_4,([] as any[]),compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n           ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_19,'name','star');
    this.renderer.setElementAttribute(this._el_19,'role','img');
    this._Icon_19_3 = new import31.Icon(this.parent.parentInjector.get(import16.Config),new import17.ElementRef(this._el_19),this.renderer);
    this._text_20 = this.renderer.createText((null as any),'\n           Read More\n         ',(null as any));
      compView_17.create(this._Button_17_4,[([] as any[]).concat([
        this._text_18,
        this._el_19,
        this._text_20
      ]
    )],(null as any));
    this._text_21 = this.renderer.createText(this._el_15,'\n       ',(null as any));
    this._text_22 = this.renderer.createText(this._el_13,'\n\n       ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_13,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_23,'text-right','');
    this._Col_23_3 = new import29.Col();
    this._text_24 = this.renderer.createText(this._el_23,'\n         ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'button',(null as any));
    this.renderer.setElementAttribute(this._el_25,'clear','');
    this.renderer.setElementAttribute(this._el_25,'color','danger');
    this.renderer.setElementAttribute(this._el_25,'icon-left','');
    this.renderer.setElementAttribute(this._el_25,'ion-button','');
    this.renderer.setElementAttribute(this._el_25,'small','');
    this._appEl_25 = new import2.AppElement(25,23,this,this._el_25);
    var compView_25:any = import32.viewFactory_Button0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Button_25_4 = new import30.Button((null as any),'',this.parent.parentInjector.get(import16.Config),new import17.ElementRef(this._el_25),this.renderer);
    this._appEl_25.initComponent(this._Button_25_4,([] as any[]),compView_25);
    this._text_26 = this.renderer.createText((null as any),'\n           ',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_27,'name','share-alt');
    this.renderer.setElementAttribute(this._el_27,'role','img');
    this._Icon_27_3 = new import31.Icon(this.parent.parentInjector.get(import16.Config),new import17.ElementRef(this._el_27),this.renderer);
    this._text_28 = this.renderer.createText((null as any),'\n           Share\n         ',(null as any));
      compView_25.create(this._Button_25_4,[([] as any[]).concat([
        this._text_26,
        this._el_27,
        this._text_28
      ]
    )],(null as any));
    this._text_29 = this.renderer.createText(this._el_23,'\n       ',(null as any));
    this._text_30 = this.renderer.createText(this._el_13,'\n     ',(null as any));
    this._text_31 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_17,'click',this.eventHandler(this._handle_click_17_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_25,'click',this.eventHandler(this._handle_click_25_0.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import28.CardContent) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._CardContent_4_3; }
    if (((token === import31.Icon) && (19 === requestNodeIndex))) { return this._Icon_19_3; }
    if (((token === import30.Button) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Button_17_4; }
    if (((token === import29.Col) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Col_15_3; }
    if (((token === import31.Icon) && (27 === requestNodeIndex))) { return this._Icon_27_3; }
    if (((token === import30.Button) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Button_25_4; }
    if (((token === import29.Col) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Col_23_3; }
    if (((token === import29.Row) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Row_13_3; }
    if (((token === import28.Card) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Card_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_5:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Button_17_4.small = currVal_5;
      changed = true;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._Button_17_4.clear = currVal_6;
      changed = true;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = 'danger';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._Button_17_4.color = currVal_7;
      changed = true;
      this._expr_7 = currVal_7;
    }
    if (changed) { this._appEl_17.componentView.markAsCheckOnce(); }
    const currVal_8:any = 'star';
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._Icon_19_3.name = currVal_8;
      this._expr_8 = currVal_8;
    }
    changed = false;
    const currVal_11:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._Button_25_4.small = currVal_11;
      changed = true;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._Button_25_4.clear = currVal_12;
      changed = true;
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = 'danger';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._Button_25_4.color = currVal_13;
      changed = true;
      this._expr_13 = currVal_13;
    }
    if (changed) { this._appEl_25.componentView.markAsCheckOnce(); }
    const currVal_14:any = 'share-alt';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._Icon_27_3.name = currVal_14;
      this._expr_14 = currVal_14;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Button_17_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_25_4.ngAfterContentInit(); }
    }
    const currVal_1:any = this.context.$implicit.img;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'src',this.viewUtils.sanitizer.sanitize(import33.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.$implicit.title,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_7,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'',this.context.$implicit.description,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_10,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_9:any = this._Icon_19_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_19,'hide',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_15:any = this._Icon_27_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_27,'hide',currVal_15);
      this._expr_15 = currVal_15;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_19_3.ngOnDestroy();
    this._Icon_27_3.ngOnDestroy();
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.itemTapped(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_17_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.itemTapped(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_25_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.shareItem(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HomePage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HomePage1(viewUtils,parentInjector,declarationEl);
}