/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './item-details';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from 'ionic-angular/components/toolbar/toolbar';
import * as import13 from 'ionic-angular/components/navbar/navbar';
import * as import14 from '@angular/common/src/directives/ng_if';
import * as import15 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import16 from 'ionic-angular/components/content/content';
import * as import17 from 'ionic-angular/config/config';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from 'ionic-angular/navigation/view-controller';
import * as import20 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import21 from 'ionic-angular/components/app/app';
import * as import22 from '@angular/core/src/linker/template_ref';
import * as import23 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import25 from 'ionic-angular/util/keyboard';
import * as import26 from '@angular/core/src/zone/ng_zone';
import * as import27 from 'ionic-angular/components/tabs/tabs';
import * as import28 from 'ionic-angular/components/button/button';
import * as import29 from 'ionic-angular/components/menu/menu-toggle';
import * as import30 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import31 from '@angular/core/src/linker/query_list';
import * as import32 from 'ionic-angular/components/icon/icon';
import * as import33 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import34 from 'ionic-angular/components/menu/menu-controller';
import * as import35 from '@angular/core/src/security';
var renderType_ItemDetailsPage_Host:import0.RenderComponentType = (null as any);
class _View_ItemDetailsPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ItemDetailsPage_0_4:import3.ItemDetailsPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ItemDetailsPage_Host0,renderType_ItemDetailsPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ItemDetailsPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ItemDetailsPage_0_4 = new import3.ItemDetailsPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams));
    this._appEl_0.initComponent(this._ItemDetailsPage_0_4,([] as any[]),compView_0);
    compView_0.create(this._ItemDetailsPage_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ItemDetailsPage) && (0 === requestNodeIndex))) { return this._ItemDetailsPage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ItemDetailsPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ItemDetailsPage_Host === (null as any))) { (renderType_ItemDetailsPage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ItemDetailsPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ItemDetailsPageNgFactory:import11.ComponentFactory<import3.ItemDetailsPage> = new import11.ComponentFactory<import3.ItemDetailsPage>('ng-component',viewFactory_ItemDetailsPage_Host0,import3.ItemDetailsPage);
const styles_ItemDetailsPage:any[] = ([] as any[]);
var renderType_ItemDetailsPage:import0.RenderComponentType = (null as any);
class _View_ItemDetailsPage0 extends import1.AppView<import3.ItemDetailsPage> {
  _el_0:any;
  _Header_0_3:import12.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import13.Navbar;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import14.NgIf;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _ToolbarTitle_6_4:import15.ToolbarTitle;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _Content_11_4:import16.Content;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _TemplateRef_13_5:any;
  _NgIf_13_6:import14.NgIf;
  _text_14:any;
  _text_15:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ItemDetailsPage0,renderType_ItemDetailsPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import12.Header(this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import19.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','primary');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import20.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import13.Navbar(this.parentInjector.get(import21.App),this.parentInjector.get(import19.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import22.TemplateRef_(this._appEl_4,viewFactory_ItemDetailsPage1);
    this._NgIf_4_6 = new import14.NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_6 = new import2.AppElement(6,2,this,this._el_6);
    var compView_6:any = import23.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(6),this._appEl_6);
    this._ToolbarTitle_6_4 = new import15.ToolbarTitle(this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_6),this.renderer,this.parentInjector.get(import12.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_6.initComponent(this._ToolbarTitle_6_4,([] as any[]),compView_6);
    this._text_7 = this.renderer.createText((null as any),'Item Details',(null as any));
    compView_6.create(this._ToolbarTitle_6_4,[([] as any[]).concat([this._text_7])],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      ([] as any[]).concat([this._appEl_4]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_5,
        this._el_6,
        this._text_8
      ]
      )
    ]
    ,(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_10 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_11 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_11 = new import2.AppElement(11,(null as any),this,this._el_11);
    var compView_11:any = import24.viewFactory_Content0(this.viewUtils,this.injector(11),this._appEl_11);
    this._Content_11_4 = new import16.Content(this.parentInjector.get(import17.Config),new import18.ElementRef(this._el_11),this.renderer,this.parentInjector.get(import21.App),this.parentInjector.get(import25.Keyboard),this.parentInjector.get(import26.NgZone),this.parentInjector.get(import19.ViewController,(null as any)),this.parentInjector.get(import27.Tabs,(null as any)));
    this._appEl_11.initComponent(this._Content_11_4,([] as any[]),compView_11);
    this._text_12 = this.renderer.createText((null as any),'\n ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_13 = new import2.AppElement(13,11,this,this._anchor_13);
    this._TemplateRef_13_5 = new import22.TemplateRef_(this._appEl_13,viewFactory_ItemDetailsPage2);
    this._NgIf_13_6 = new import14.NgIf(this._appEl_13.vcRef,this._TemplateRef_13_5);
    this._text_14 = this.renderer.createText((null as any),'\n',(null as any));
    compView_11.create(this._Content_11_4,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_12,
        this._appEl_13,
        this._text_14
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_15 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._text_15
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import14.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6; }
    if (((token === import15.ToolbarTitle) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarTitle_6_4; }
    if (((token === import13.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Navbar_2_4; }
    if (((token === import12.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Header_0_3; }
    if (((token === import22.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import14.NgIf) && (13 === requestNodeIndex))) { return this._NgIf_13_6; }
    if (((token === import16.Content) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Content_11_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'primary';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Navbar_2_4.color = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_3:boolean = !this.context.selectedItem;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_4_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_11_4.ngOnInit(); }
    const currVal_5:any = this.context.selectedItem;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgIf_13_6.ngIf = currVal_5;
      this._expr_5 = currVal_5;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_4:any = this._Content_11_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_11,'statusbar-padding',currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_11_4.ngOnDestroy();
  }
}
export function viewFactory_ItemDetailsPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ItemDetailsPage> {
  if ((renderType_ItemDetailsPage === (null as any))) { (renderType_ItemDetailsPage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_ItemDetailsPage,{})); }
  return new _View_ItemDetailsPage0(viewUtils,parentInjector,declarationEl);
}
class _View_ItemDetailsPage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Button_0_4:import28.Button;
  _MenuToggle_0_5:import29.MenuToggle;
  _ToolbarItem_0_6:import30.ToolbarItem;
  _query_Button_0_0:import31.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import32.Icon;
  _text_3:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ItemDetailsPage1,renderType_ItemDetailsPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'ion-button','');
    this.renderer.setElementAttribute(this._el_0,'menuToggle','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import33.viewFactory_Button0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Button_0_4 = new import28.Button('','',this.parent.parentInjector.get(import17.Config),new import18.ElementRef(this._el_0),this.renderer);
    this._MenuToggle_0_5 = new import29.MenuToggle(this.parent.parentInjector.get(import34.MenuController),new import18.ElementRef(this._el_0),this.parent.parentInjector.get(import19.ViewController,(null as any)),(<_View_ItemDetailsPage0>this.parent)._Navbar_2_4);
    this._ToolbarItem_0_6 = new import30.ToolbarItem(this.parent.parentInjector.get(import17.Config),new import18.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import12.Toolbar,(null as any)),(<_View_ItemDetailsPage0>this.parent)._Navbar_2_4);
    this._query_Button_0_0 = new import31.QueryList<any>();
    this._appEl_0.initComponent(this._Button_0_4,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'name','menu');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import32.Icon(this.parent.parentInjector.get(import17.Config),new import18.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_0.create(this._Button_0_4,[([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_3
      ]
    )],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import32.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3; }
    if (((token === import28.Button) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Button_0_4; }
    if (((token === import29.MenuToggle) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MenuToggle_0_5; }
    if (((token === import30.ToolbarItem) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ToolbarItem_0_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._MenuToggle_0_5.menuToggle = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_3:any = 'menu';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Icon_2_3.name = currVal_3;
      this._expr_3 = currVal_3;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_0.dirty) {
        this._query_Button_0_0.reset([this._Button_0_4]);
        this._ToolbarItem_0_6._buttons = this._query_Button_0_0;
        this._query_Button_0_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_0_4.ngAfterContentInit(); }
    }
    const currVal_2:any = this._MenuToggle_0_5.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_0,'hidden',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_4:any = this._Icon_2_3._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_2_3.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_0_5.toggle()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ItemDetailsPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ItemDetailsPage1(viewUtils,parentInjector,declarationEl);
}
class _View_ItemDetailsPage2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ItemDetailsPage2,renderType_ItemDetailsPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','selection');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'b',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'img',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.selectedItem,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.parent.context.image;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_5,'src',this.viewUtils.sanitizer.sanitize(import35.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ItemDetailsPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ItemDetailsPage2(viewUtils,parentInjector,declarationEl);
}